FROM docker.elastic.co/kibana/kibana:8.15.0

ENV ELASTICSEARCH_HOSTS=https://kwik-nesta-elasticsearch.onrender.com:9200
ENV SERVER_PUBLICBASEURL=https://kwik-nesta-kibana.onrender.com
ENV XPACK_SECURITY_ENABLED=false

EXPOSE 5601